

name: CI


on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: login_in
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN}}
      - run: |
         docker build -t ghcr.io/h0lonar/380-node-2-app:1.0 node/

         docker push ghcr.io/h0lonar/380-node-2-app:1.0

         docker build -t ghcr.io/h0lonar/380-node-2-app:1.0 python/

         docker push ghcr.io/h0lonar/380-python-2-app:1.0

      - name:  Run a multi-line script
      

         

